version: '3'
services:
  # spring:
  #   image: openjdk:17.0.2-jdk-oraclelinux8
  #   container_name: spring_container
  #   restart: always
  #   working_dir: /app
  #   ports:
  #     - 82:8080
  #   networks:
  #     - vlsg_network
  #   volumes:
  #     - ./backend/spring/target/spring-0.0.1-SNAPSHOT.jar:/app/server.jar
  #   command: "java -jar server.jar"
  #   depends_on:
  #     - db

  spring_dev:
    container_name: spring_dev_container
    build: backend/spring
    restart: always
    working_dir: /app
    ports:
      - 3000:8080
    networks:
      - vlsg_network
    volumes:
      - ./backend/spring:/app
      - ./configuration/spring:/app/src/main/resources
    command: "mvn spring-boot:run"
    depends_on:
      - db